
pipeline{
    agent any

    stages{
        stage('Checkout'){
            steps{
                //Clonar repositorio git
                git url: 'https://github.com/Axors3/Proyecto-DevOps.git',branch: 'feature/Jenkins'

            }
        }
        stage('Install dependencies'){
            steps{
                //sh 'npm install'
                bat 'npm install'
            }
        }

    }
}

/*
pipeline {
    agent any
    stages {
        stage('Pipeline 1') {
            steps {
                script {
                    pipeline {
                        agent any
                        stages {
                            stage('Checkout') {
                                steps {
                                    //Clonar repositorio git
                                    git url: 'https://github.com/Axors3/Proyecto-DevOps.git',branch: 'feature/Jenkins'
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('Pipeline 2') {
            steps {
                script {
                    pipeline {
                        agent any
                        stages {
                            stage('Install dependencies') {
                                steps {
                                    //sh 'npm install'
                                    bat 'npm install'
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
*/