
pipeline{
    agent any

    stages{
        stage('Pipeline 1'){
            steps{
                //Clonar el proyecto
                git url: 'https://github.com/Axors3/Proyecto-DevOps.git',branch: 'feature/Jenkins'

                //Construccion del proyecto
                //sh 'npm install'
                bat 'npm install'

                //Correr test cases
                echo "Todo chido"

            }
        }
        stage('Pipeline 2'){
            steps{
                //Crear Imagen de Docker
                bat "docker build --tag uadyphone-api-feature/Jenkins ."

                //Correr Image
                bat "docker run --detach uadyphone-api-feature/Jenkins"
            }
        }

    }
}

